global:
  first_setting: value1
  second_setting: value2

development:
  first_setting: value1
  second_setting: value2

test:
  first_setting: value1
  second_setting: value2

production:
  first_setting: value1
  second_setting: value2
